# Generated by Django 5.0.7 on 2025-04-14 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paypal_txn_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='stripe_session_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('stripe', 'Stripe/Card/Apple Pay'), ('paypal', 'PayPal')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_cents',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.package'),
        ),
    ]
