# Generated by Django 5.0.7 on 2025-04-14 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_payment_paypal_txn_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='home.package'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='home/'),
        ),
    ]
