# Generated by Django 5.0.7 on 2025-04-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_payment_package_alter_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price_cents',
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
