# Generated by Django 5.0.7 on 2025-04-15 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_package_price_cents_alter_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.CharField(choices=[('usd', 'US Dollar'), ('pkr', 'Pakistani Rupee')], default='usd', max_length=3),
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in dollars', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.package'),
        ),
    ]
