# Generated by Django 5.0.7 on 2025-04-15 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_package_currency_package_price_alter_payment_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.AlterField(
            model_name='payment',
            name='package',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='home.package'),
        ),
    ]
