# Generated by Django 5.0.7 on 2025-04-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_package_currency_remove_package_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price_cents',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
