# Generated by Django 5.0.7 on 2025-04-15 06:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_package_price_cents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='package',
            name='video',
        ),
        migrations.RemoveField(
            model_name='package',
            name='num_videos',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price_cents',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_cents',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='package',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=False, help_text='Price for this package.', max_digits=8),
        ),
        migrations.AddField(
            model_name='package',
            name='video_details',
            field=models.CharField(default=False, help_text="Details such as '1000 videos with licence'.", max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=False, help_text='The amount paid.', max_digits=8),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('card', 'Credit/Debit Card'), ('apple_pay', 'Apple Pay'), ('other', 'Other')], default=False, help_text='Select a payment method.', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], help_text='Type of package: Standard or Premium.', max_length=20),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.URLField(help_text='URL to the service explanation video')),
                ('description', models.TextField(blank=True, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, default=False, help_text='If this service is offered at a fixed price.', max_digits=8, null=True)),
                ('has_multiple_packages', models.BooleanField(default=False, help_text='Check if the service provides multiple pricing packages (e.g., Standard and Premium).')),
                ('payment_methods', models.ManyToManyField(blank=True, help_text='Select the payment methods accepted for this service.', to='home.paymentmethod')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ForeignKey(default=False, help_text='The service to which this package belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='home.service'),
        ),
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(default=False, help_text='The service associated with this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.service'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
