# Generated by Django 5.0.7 on 2025-04-15 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_paymentmethod_remove_package_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('card', 'Card'), ('apple_pay', 'Apple Pay'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.video'),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
