# Generated by Django 5.0.7 on 2025-04-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
