# Generated by Django 5.0.7 on 2025-04-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('card', 'Card'), ('apple_pay', 'Apple Pay'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='video',
            name='Description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
