# Generated by Django 5.0.7 on 2025-04-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_payment_payment_method_alter_video_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the reviewer.', max_length=255)),
                ('remarks', models.TextField(help_text="Reviewer's remarks.")),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Very Poor'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], help_text='Rating from 1 to 5.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the review was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the review was last updated.')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
